### ISSUE TITLE
eval_output drops extra lines when merging sim and meas

### ISSUE THREAD

**Issue by mariegosme** [VEZY/sticRs#7]
Salut Remy, je suis avec Kirsten et on est tombées sur un comportement bizarre: certaines années, quand la dernière date mesurée est après la dernière date simulée, le mergeage des deux dataframes (lignes 57 et 69 de eval_output) ne garde pas les lignes de meas qui ne sont pas dans sim (car all.y=F), donc si les données mesurées sont dans ces dates, la fonction stics_eval plante car il n'y a aucune donnée observée.
 C'est facile à corriger, il suffit de mettre all.y=TRUE (mais peut-être y a-t-il une autre raison pour laquelle all.y=F
. Cordialement. Marie

**Comment by VEZY** [comment]
Salut Marie,
je n'arrive pas à reproduire l'erreur de mon côté. J'ai bien des dates supérieures à la fin de la simulation, et je n'ai pas d'erreur. J'ai aussi testé en ne mettant **que** des dates supérieures à la simulation pour n'avoir que des dates non communes, et la fonction termine le job avec ce warning comme prévu: 
![image](https://user-images.githubusercontent.com/12777793/52910626-9bb20b80-329a-11e9-8f3d-38a1b9dc7f2b.png)

Peut-être que je comprends pas bien votre erreur. Est-ce que vous pourriez m'envoyer le jeu de données et le code associé pour que je puisse reproduire l'erreur ?
